version: '3'

networks:
  mynetwork:
    driver: bridge
services:
  infinispan-server-lon-1:
    image: quay.io/infinispan/server:15.1
    ports:
      - "11222:11222"
    container_name: ispn-lon-1
    environment:
      USER: admin
      PASS: pass
    networks:
      - mynetwork
    command: -c infinispan-xsite.xml -Dinfinispan.site.name=LON -Djgroups.mcast_port=46656
  infinispan-server-lon-2:
    image: quay.io/infinispan/server:15.1
    ports:
      - "11221:11222"
    container_name: ispn-lon-2
    environment:
      USER: admin
      PASS: pass
    networks:
      - mynetwork
    command: -c infinispan-xsite.xml -Dinfinispan.site.name=LON -Djgroups.mcast_port=46656
  infinispan-server-lon-3:
      image: quay.io/infinispan/server:15.1
      ports:
        - "11223:11222"
      container_name: ispn-lon-3
      environment:
        USER: admin
        PASS: pass
      networks:
        - mynetwork
      command: -c infinispan-xsite.xml -Dinfinispan.site.name=LON -Djgroups.mcast_port=46656
  infinispan-server-nyc-1:
    image: quay.io/infinispan/server:15.1
    ports:
      - "31222:11222"
    container_name: ispn-nyc-1
    environment:
      USER: admin
      PASS: pass
    networks:
      - mynetwork
    command: -c infinispan-xsite.xml -Dinfinispan.site.name=NYC -Djgroups.mcast_port=46666